site_name: Education @ Software + ML
site_url: https://education.softwareplus.ml
site_description: Stories and Codes from Research to Production
repo_url: https://github.com/baluyotraf/softwareplusml-education
repo_name: baluyotraf/softwareplusml-education
edit_uri: ""
copyright: Copyright &copy; 2022 Raffaello Baluyot

nav:
  - Home: index.md
  - Projects:
    - Neural Networks: projects/neural-networks.md

plugins:
  - include-markdown

plugins:
  - include-markdown
  - social

theme:
  name: material
  language: en
  palette:
    primary: red
    accent: light blue
  icon:
    logo: fontawesome/solid/graduation-cap
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/baluyotraf/
      name: baluyotraf
    - icon: fontawesome/brands/github
      link: https://github.com/baluyotraf
      name: baluyotraf
